title: Adolfo Neto
description: Elixir and Erlang enthusiast. Associate Professor at UTFPR

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - research.md

theme: jekyll-theme-dinky
